### ISSUE TITLE
Requester stations turn into provider stations

### ISSUE THREAD

**Issue by tehasdf** [Yousei9/Factorio-LogisticTrainNetwork#33]
Hi,
I'm facing an issue in my game where a station I've set up to request some item, starts providing that item - so trains come to that station waiting to be loaded, but of course that never happens, since I only have unloading inserters there :)

I do have a decider combinator that makes sure only negative counts are ever emitted to the station input signal.

However, here's a log from the game:
```
8044.341 Script interface.lua:46: [LTN] (UpdateStop) Simple smelting.in(quartz)[1] updating requested count with delivery: item,quartz -101138 + 64000
8044.341 Script interface.lua:46: [LTN] (UpdateStop) Simple smelting.in(quartz)[1] updating requested count with delivery: item,quartz -37138 + 64000
8044.341 Script interface.lua:46: [LTN] (UpdateStop) Simple smelting.in(quartz)[1] updating requested count with delivery: item,quartz 26862 + 15857
8044.341 Script interface.lua:46: [LTN] (UpdateStop) Simple smelting.in(quartz)[1] updating provided count with train inventory: item,quartz 42719 - 8060
```

As you can see, the initial circuit count (-101138) was tipped above 0 by registered incoming deliveries, which made the station register as a provider. I think this all happened in one call of the `UpdateStop` function, so there's really nothing you can do ingame to prevent that.

I think the logic for deciding whether a station is a provider here: https://github.com/Yousei9/Factorio-LogisticTrainNetwork/blob/master/control.lua#L1373 should not take into account the deliveries that just registered, so perhaps it should simply use the value from the circuit network, before adding incoming deliveries.

**Comment by Yousei9** [comment]
Assigning deliveries totaling to more than request amount can only happen when changing requested amount after those deliveries where dispatched.
Once those excess items are delivered that requester will turn into a provider no matter what I do.

LTN updates provided and requested amounts to prevent exactly such situations in normal operation.

Best Practice for changing requested amount is to turn off the constant combinator while editing the values.

**Comment by tehasdf** [comment]
>Even if i added a check against this overflow during delivery, the requester will become a provider once these deliveries have unloaded.
No, that can and will be prevented by a decider combinator not allowing positive values to the train stop input.

Also, this has nothing to do with changing the requested amounts - in fact, the stations where this happens in my game, were never changed.

@Yousei9 follow the code starting here: https://github.com/Yousei9/Factorio-LogisticTrainNetwork/blob/master/control.lua#L1326 and imagine there's a -10k from circuitValues, then +20k from a train here: https://github.com/Yousei9/Factorio-LogisticTrainNetwork/blob/master/control.lua#L1343 - now `count` is positive, as you can see in my logs, so we go here: https://github.com/Yousei9/Factorio-LogisticTrainNetwork/blob/master/control.lua#L1373 and are a provider. Which breaks.

**Comment by Yousei9** [comment]
Why is there more delivered than requested?
If your circuit values add up to -10k (what LTN sees) there won't be a 20k delivery.

**Comment by tehasdf** [comment]
Seems that happens because of `finish_loading`. See the log here: https://gist.github.com/tehasdf/443241f2f97a042392673d4d95078bd5
The station "Cotusiepierdoli" requested 100k tin ore, so LTN  created a 64k + 36k delivery. In the tick 4599.907 there you can see that those are the values, but in the next tick, the 36k train got overloaded by inserters (due to `finish_loading`) - and in each next tick, there's more tin ore in it (up to 64k), so in each next tick, the station says it provides tin ore.

**Comment by Yousei9** [comment]
Finish loading requires your stations to be smart.
![Provider](https://forums.factorio.com/download/file.php?id=24841)

**Comment by tehasdf** [comment]
Sure. So, if you ever decide to fix this bug after all, here's the patch I'm using: https://gist.github.com/tehasdf/53598f49f86485d866f3f61e175df49a

(or for anyone else who stumbles upon this issue)

**Comment by Yousei9** [comment]
Fixed in 1.2.8

**Comment by Bronzeborg** [comment]
i still have this issue. https://imgur.com/a/hAdEm5j i did have the chest be a buffer chest set to fill the chest tough. could that be the issue? that the chest is already full so ltn thinks its a provider?

**Comment by Yousei9** [comment]
No you do not have this issue.
You just have a requester that got overfilled to the point where it was above provide threshold.

Use unreachable high, e.g. 1M, provide threshold on requester.
